version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
#      - dependency-name: "setuptools"
#        versions: ["69.0.3"]
