version: 2
updates:
  - package-ecosystem: "pip"
    allow:
      - dependency-type: "all"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
#    ignore:
#      - dependency-name: "setuptools"
#        versions: ["69.0.3"]
