name: Run Tests

on:
  #  release:
  #    types: [created]
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"
      - name: Run tests
        run: pytest
